@startuml ARCHI
interface Instrument {
  +getUnderlying()
  +getStrike()
  +getMaturity()
}

class VanillaOption {
  -strike: double
  -maturity: LocalDate
  -isCall: boolean
  -id: String
  -underlying: String
}

class OptionQuoteRow {
  -underlyingLast: double
  -strike: double
  -expireDate: LocalDate
  -callIV: double
  -putIV: double
  -callBid: double
  -callAsk: double
  -putBid: double
  -putAsk: double
  -callVolume: double
  -putVolume: double
}

class MarketData {
  -asOf: LocalDate
  -spot: double
  -assumptions: MarketDataAssumptions
  -impliedVolSurface: ImpliedVolSurface
}

interface MarketDataSource {
  +MarketData load(LocalDate date)
}

class MarketDataParquet {
  -filePath: String
  -assumptions: MarketDataAssumptions
}

class MarketDataAssumptions {
  -riskFreeRate: double
  -dividendYield: double
}

class ImpliedVolSurface {
  -points: List<VolPoint>
  +getVol(strike: double, expireDate: LocalDate): double
  +size(): int
}

class VolPoint <<static>> {
  -strike: double
  -expireDate: LocalDate
  -vol: double
}

ImpliedVolSurface +-- VolPoint
MarketDataParquet ..> OptionQuoteRow : uses
VanillaOption ..|> Instrument : implements
MarketDataSource ..> MarketData : produces
MarketDataAssumptions <-- MarketData : uses
MarketDataParquet ..|> MarketDataSource : implements
MarketData --> ImpliedVolSurface : uses
@enduml